"""empty message

Revision ID: 86ef8896e578
Revises: 8d209c37fff1
Create Date: 2021-07-18 23:55:00.201014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ef8896e578'
down_revision = '8d209c37fff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('date', sa.String(length=100), nullable=True))
    op.add_column('comment', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('stock', sa.Column('link_lamoda', sa.String(length=100), nullable=True))
    op.drop_column('stock', 'link_wildberries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('link_wildberries', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('stock', 'link_lamoda')
    op.drop_column('comment', 'author')
    op.drop_column('comment', 'date')
    # ### end Alembic commands ###
